services:
  csharp-dotnet-generic-impulse:
    image: bkataru/impulses:csharp-dotnet-generic
    container_name: csharp-dotnet-generic-impulse-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    tty: true
    stdin_open: true
    command: "/bin/bash"